### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by ChihChengLiang**
Open a draft PR here to track how much we need to fix for the test to run

### CODE REVIEW

**Comment by vaibhavchellani** [comment]
feel free to remove tests that are too much work to fix

**Comment by ChihChengLiang** [comment]
The tests runs well in CI, but I'm getting this issue https://github.com/kilic/bn254/issues/2 when running tests on my macOS locally.

**Comment by vaibhavchellani** [comment]
Do we want to merge this @ChihChengLiang

**Comment by ChihChengLiang** [comment]
yes if it looks good to you.

**Review by vaibhavchellani — APPROVED** [review]
LGTM!

**Pull request merged**
